# Docker Compose version
version: "3.7"
services:
  # MySQL
  mysql:
    image: mariadb:10.8
    volumes:
      - db:/var/lib/mysql
      - ../../etc/data/mysql:/data
      - ../containers/mysql:/etc/mysql/conf.d
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ally
      MYSQL_USER: ally
      MYSQL_PASSWORD: ally

  # ally
  ally:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: example/docker/containers/ally/Dockerfile
    environment:
      ALLY_ENVIRONMENT: development
      ALLY_SERVER_PORT: 3000
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ../../:/ally

# Volumes
volumes:
  db:
