# Docker Compose version
version: "3.7"
services:
  # Redis
  redis:
    image: amd64/redis:alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: redis-server --requirepass ally
  # postgresql
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ally
      - POSTGRES_PASSWORD=ally
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # ally
  ally:
    depends_on:
      - postgresql
    build:
      context: ../
      dockerfile: docker/containers/ally/Dockerfile
    environment:
      ALLY_ENVIRONMENT: development
      ALLY_SERVER_PORT: 3000
      ALLY_DB_HOST: postgresql
      ALLY_DB_PORT: 5432
      ALLY_DB_USER: ally
      # ALLY_DB_PASSWORD: ally
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ../:/ally

# Volumes
volumes:
  db:
    driver: local
